### PR TITLE
Basic demos for LaTeX/plain/ConTeXt

### PR DESCRIPTION
**Pull request by josephwright**
This is a set of basic demos of `l3build` for common formats. I've included one test using a PDF, the rest are log-based. Note that the tests are split up by format as at present that's how `l3build` works. Also notice that ConTeXt probably needs a bit of work yet!

PDF-based testing is still in development so might need further tweaking/options.

### CODE REVIEW

**Comment by norbusan** [comment]
Hi David,

thanks a lot for the examples, they are very useful!

May I asked a few questions:
- the context test runs indefinitely waiting for input, a Ctrl-D terminates and gives failed test
- the latex test also fails with an additional line `(.aux)` at the end of latex001
- shouldn't the build directory by in .gitignore as it should be recreated on demand?

All the best

Norbert

**Comment by josephwright** [comment]
Hi @norbusan,

I'm making some updates to `l3build` to support various aspects here. In particular, we've not looked at ConTeXt in detail before. The release version of `l3build` currently won't work, but it should do if you try the one from our Git repo. I'm still adding some features so will make another pull request later today/tomorrow to update the code here.

On the hang, the automation we have for testing (Travis-CI) has a monitoring approach: if there is no output for 10 mins the tests fail and are killed. I'm not sure what you plan to do longer-term but it's impossible to avoid TeX sitting at a prompt for a missing file, so something like that is required.

I've found a few fresh bugs in `l3build` which show up here with the `.aux` file business. I've got a couple of items to check: again, give me 24 h.

On the `.gitignore`, this is just how I do things to avoid needing to worry about the scratch dir. Adjust however you like :-)

**Comment by norbusan** [comment]
Perfect, thanks, no hurry - I am soon off for travels to remote corners ;-)

**Comment by icebearsoft** [comment]
I have a small script written in expect. If there is no output within a
specified time (default 30 seconds), the program is stopped. I use it when
running TeX from an IDE where a console is not available. Will you be
interested?

Zdeněk Wagner
http://ttsm.icpf.cas.cz/team/wagner.shtml
http://icebearsoft.euweb.cz

2016-06-22 8:03 GMT+02:00 Norbert Preining notifications@github.com:

**Comment by josephwright** [comment]
@icebearsoft Down to @norbusan  I guess. For local testing you can soon see that things have hung: it's more on the automated side that a script is required. I'm not sure how this might be put together.

**Comment by icebearsoft** [comment]
016-06-22 10:34 GMT+02:00 Joseph Wright notifications@github.com:

> @icebearsoft https://github.com/icebearsoft Down to @norbusan
> https://github.com/norbusan I guess. For local testing you can soon see
> that things have hung: it's more on the automated side that a script is
> required. I'm not sure how this might be put together.

The usage is quite simple:

run-while-living.exp [timeout] command arg1 arg2 arg3 ...

I do not currently return the status code of the command so it is just
possible to test whether the command ran to its end or whether if was
interrupted because it hanged. In your script you just invoke each TeX
execution through run-while-living.exp. The disadvantage is that you must
have expect installed.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/TeX-Live/tltesting/pull/1#issuecomment-227678331, or mute
> the thread
> https://github.com/notifications/unsubscribe/ATIndJBmg8lnf6EIvFr5OwFGM3WuN8r8ks5qOPOTgaJpZM4I670Z
> .

Zdeněk Wagner
http://ttsm.icpf.cas.cz/team/wagner.shtml
http://icebearsoft.euweb.cz

2

**Comment by norbusan** [comment]
Hi all,

Zdenek, yes, please simple commit the file to say a`tools` directory in the `tltesting` repository. If you need git guidance, let me know.

I want to lay out my imaginative solution here ... don't laugh at me.

What I really would like to see is that, whenever a commit is sent to the TeX Live subversion repository, a test run is started for each file, or for each file that matches a certain list of files or patterns.

For each selected file, if nothing is overridden in some way (by the author, etc etc to be specified), a set of default tests is run on the file. For `.sty` files a simple loading test, for `.cls` files the same, etc etc.

If one of the test fails, an email is sent to Karl/me/whoever to investigate it (but do not reject the commit).

At the same time it should be possible to run the same tests on my local system by some wonderful invocations.

Does that sound reasonable for you?

**Comment by josephwright** [comment]
@norbusan  That's one aspect of continuous integration (CI), so it's quite doable, it's  a question of how much effort you make vs. how much you can 'farm out'. For the LaTeX team stuff, we've only got CI set up at present for LaTeX3 work not for LaTeX2e, mainly because the LaTeX3 code is mirrored to GitHub and there are various people offering CI solutions which link automatically to GitHub pushes. For SVN I'm not sure if there are this sort of easy 'service' sites available but you can definitely set up a VM to do the job on some local system. Just a question of doing the work.

**Comment by norbusan** [comment]
@josephwright thanks, but I was more thinking of a subversion post-commit hook. That is something we can do by ourselves. It would simply chdir to a test dir, copy the respective files, and run TeX from the otherwise up2date subversion master. That is my plan ;-) No need for a special CI solution.

**Comment by norbusan** [comment]
PS, we actually already think about doing post-commit-hook check on perl stupid errors ... ;-)

**Comment by josephwright** [comment]
I guess the one tricky part is the 'pattern' business: the normal approach for CI systems is to test 'everything', but that's based around the idea that the scale is reasonable. Probably you can get the info from the log into a script and from there work out which tests to run.

**Comment by norbusan** [comment]
Yes, that is the idea. The post-commit hook has access to the changed files, and also to say a master list of files/patterns to be tested.

**Comment by norbusan** [comment]
I just realized that the post-commit-hook is probably overkill, and it would be easier to have a cron job that once a day runs over the commits, tests the files, and sends out problem reports. Actually much better, as we are generally not working on one project=file from various people, but simply committing new versions of files from CTAN.

**Comment by josephwright** [comment]
@norbusan  Only issue with a cron job is that you loose the ability to pin down which commit was an issue, at least without digging. However, for the TL situation that's probably OK. I guess you'd do something like 'Run the tests, saving the output to a file. If the errorlevel is zero, delete the file, otherwise mail the output to [people].' Logic needs to include the ability to spot that the tests have hung and kill them (already discussed).

**Comment by norbusan** [comment]
Yes, in our case this is not a problem, that is what I meant with the "not working on one project=file" part. Normal commits are updates from CTAN, that means there is at most one per day for a certain package (file).

Of course, the `tlmgr` and perl modules could use unit tests and CI tests, but that is not what we are targeting here - although definitely high on my priority list.

**Pull request merged**
